/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Chat */
        post: operations["chat_v1_chat_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/conversations/{conversation_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Conversation */
        delete: operations["delete_conversation_v1_conversations__conversation_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/announcements": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Announcements */
        get: operations["announcements_v1_announcements_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/ingest/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ingest Documents */
        post: operations["ingest_documents_v1_admin_ingest_documents_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/crawl/announcements": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Crawl Announcements */
        post: operations["crawl_announcements_v1_admin_crawl_announcements_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/site-map/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sync Site Map */
        post: operations["sync_site_map_v1_admin_site_map_sync_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/crawl/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Crawl Status */
        get: operations["crawl_status_v1_admin_crawl_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/site-map/crawl/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Crawl Status */
        get: operations["crawl_status_v1_admin_site_map_crawl_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/crawl/schedule": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Schedule Crawl */
        post: operations["schedule_crawl_v1_admin_crawl_schedule_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/site-map/crawl/schedule": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Schedule Crawl */
        post: operations["schedule_crawl_v1_admin_site_map_crawl_schedule_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AnnouncementItem */
        AnnouncementItem: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** Unit */
            unit: string;
            /** Category */
            category?: string | null;
            /**
             * Published At
             * Format: date
             */
            published_at: string;
            /** Deadline At */
            deadline_at?: string | null;
            /** Canonical Url */
            canonical_url: string;
        };
        /** AnnouncementListResponse */
        AnnouncementListResponse: {
            /** Items */
            items: components["schemas"]["AnnouncementItem"][];
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
            /** Total */
            total: number;
        };
        /**
         * AnswerType
         * @enum {string}
         */
        AnswerType: "official_document" | "announcement" | "insufficient_information";
        /** ChatRequest */
        ChatRequest: {
            /** Question */
            question: string;
            /** Conversation Id */
            conversation_id?: string | null;
        };
        /** ChatResponse */
        ChatResponse: {
            /** Conversation Id */
            conversation_id: string;
            /** Answer */
            answer: string;
            answer_type: components["schemas"]["AnswerType"];
            confidence: components["schemas"]["Confidence"];
            /** Sources */
            sources: components["schemas"]["SourceReference"][];
            /** Warning */
            warning?: string | null;
        };
        /**
         * Confidence
         * @enum {string}
         */
        Confidence: "high" | "medium" | "low";
        /** CrawlRequest */
        CrawlRequest: {
            /** Source Names */
            source_names?: string[] | null;
        };
        /** CrawlScheduleRequest */
        CrawlScheduleRequest: {
            /** Source Names */
            source_names?: string[] | null;
            /** Urls */
            urls?: string[] | null;
            /** Unit */
            unit?: string | null;
            /** Host */
            host?: string | null;
            /** Page Type */
            page_type?: string | null;
            /** Run At */
            run_at?: string | null;
            /**
             * Delay Seconds
             * @default 0
             */
            delay_seconds: number;
            /**
             * Dry Run
             * @default false
             */
            dry_run: boolean;
        };
        /** CrawlScheduleResponse */
        CrawlScheduleResponse: {
            /**
             * Status
             * @default scheduled
             */
            status: string;
            /** Schedule Id */
            schedule_id: string;
            /**
             * Scheduled At
             * Format: date-time
             */
            scheduled_at: string;
            /**
             * Run At
             * Format: date-time
             */
            run_at: string;
            /** Source Names */
            source_names?: string[];
            /**
             * Dry Run
             * @default false
             */
            dry_run: boolean;
            /**
             * Scheduled Pages
             * @default 0
             */
            scheduled_pages: number;
        };
        /** CrawlStatusResponse */
        CrawlStatusResponse: {
            /** Status */
            status: string;
            /**
             * Enabled
             * @default true
             */
            enabled: boolean;
            /** Interval Seconds */
            interval_seconds?: number | null;
            /** Run Id */
            run_id?: string | null;
            /** Last Run At */
            last_run_at?: string | null;
            /** Last Success At */
            last_success_at?: string | null;
            /** Last Error */
            last_error?: string | null;
            /**
             * Runs Total
             * @default 0
             */
            runs_total: number;
            /**
             * Successes Total
             * @default 0
             */
            successes_total: number;
            /**
             * Failures Total
             * @default 0
             */
            failures_total: number;
            /**
             * Schedules Total
             * @default 0
             */
            schedules_total: number;
            /**
             * Queue Depth
             * @default 0
             */
            queue_depth: number;
            /** Last Run Status */
            last_run_status?: string | null;
            /**
             * Last Sources Attempted
             * @default 0
             */
            last_sources_attempted: number;
            /**
             * Last Sources Succeeded
             * @default 0
             */
            last_sources_succeeded: number;
            /**
             * Last Sources Failed
             * @default 0
             */
            last_sources_failed: number;
            /**
             * Last Created
             * @default 0
             */
            last_created: number;
            /**
             * Last Updated
             * @default 0
             */
            last_updated: number;
            /**
             * Last Unchanged
             * @default 0
             */
            last_unchanged: number;
            /**
             * Last Failed
             * @default 0
             */
            last_failed: number;
            /** Last Errors */
            last_errors?: string[];
            /** Last Duration Ms */
            last_duration_ms?: number | null;
            /** Next Run At */
            next_run_at?: string | null;
            /** Pending Schedule Id */
            pending_schedule_id?: string | null;
            /**
             * Dry Run
             * @default false
             */
            dry_run: boolean;
            /**
             * Pending
             * @default 0
             */
            pending: number;
            /**
             * Due
             * @default 0
             */
            due: number;
            /**
             * Leased
             * @default 0
             */
            leased: number;
            /**
             * Failed
             * @default 0
             */
            failed: number;
            /**
             * Blocked
             * @default 0
             */
            blocked: number;
            /**
             * Pending Ingestion
             * @default 0
             */
            pending_ingestion: number;
            /**
             * Incomplete Ingestion
             * @default 0
             */
            incomplete_ingestion: number;
            /**
             * Active Workers
             * @default 0
             */
            active_workers: number;
            /** Next Due At */
            next_due_at?: string | null;
            /** Recent Attempts */
            recent_attempts?: {
                [key: string]: number;
            };
        };
        /** CrawlSummary */
        CrawlSummary: {
            /**
             * Created
             * @default 0
             */
            created: number;
            /**
             * Updated
             * @default 0
             */
            updated: number;
            /**
             * Unchanged
             * @default 0
             */
            unchanged: number;
            /**
             * Failed
             * @default 0
             */
            failed: number;
            /** Errors */
            errors?: string[];
        };
        /** ErrorBody */
        ErrorBody: {
            /** Code */
            code: string;
            /** Message */
            message: string;
            /** Details */
            details?: unknown | null;
            /** Request Id */
            request_id: string;
        };
        /** ErrorResponse */
        ErrorResponse: {
            error: components["schemas"]["ErrorBody"];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** IngestionSummary */
        IngestionSummary: {
            /**
             * Created
             * @default 0
             */
            created: number;
            /**
             * Skipped
             * @default 0
             */
            skipped: number;
            /**
             * Failed
             * @default 0
             */
            failed: number;
            /** Errors */
            errors?: string[];
        };
        /** SiteMapSyncResponse */
        SiteMapSyncResponse: {
            /**
             * Seen
             * @default 0
             */
            seen: number;
            /**
             * Created
             * @default 0
             */
            created: number;
            /**
             * Updated
             * @default 0
             */
            updated: number;
            /**
             * Skipped
             * @default 0
             */
            skipped: number;
            /**
             * Failed
             * @default 0
             */
            failed: number;
            /**
             * Links Created
             * @default 0
             */
            links_created: number;
        };
        /** SourceReference */
        SourceReference: {
            /** Id */
            id: string;
            kind: components["schemas"]["AnswerType"];
            /** Title */
            title: string;
            /** Url */
            url: string;
            /** Unit */
            unit: string;
            /** Published At */
            published_at: string | null;
            /**
             * Source Type
             * @default official
             * @constant
             */
            source_type: "official";
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description 統一錯誤 envelope */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 統一錯誤 envelope */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    chat_v1_chat_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatResponse"];
                };
            };
            /** @description 統一錯誤 envelope */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 統一錯誤 envelope */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 統一錯誤 envelope */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 統一錯誤 envelope */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    delete_conversation_v1_conversations__conversation_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description 統一錯誤 envelope */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 統一錯誤 envelope */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 統一錯誤 envelope */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    announcements_v1_announcements_get: {
        parameters: {
            query?: {
                q?: string | null;
                unit?: string | null;
                date_from?: string | null;
                date_to?: string | null;
                page?: number;
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnnouncementListResponse"];
                };
            };
            /** @description 統一錯誤 envelope */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 統一錯誤 envelope */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 統一錯誤 envelope */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    ingest_documents_v1_admin_ingest_documents_post: {
        parameters: {
            query?: never;
            header?: {
                "X-Admin-Key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestionSummary"];
                };
            };
            /** @description 統一錯誤 envelope */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 統一錯誤 envelope */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description 統一錯誤 envelope */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 統一錯誤 envelope */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 統一錯誤 envelope */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    crawl_announcements_v1_admin_crawl_announcements_post: {
        parameters: {
            query?: never;
            header?: {
                "X-Admin-Key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["CrawlRequest"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CrawlSummary"];
                };
            };
            /** @description 統一錯誤 envelope */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 統一錯誤 envelope */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 統一錯誤 envelope */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 統一錯誤 envelope */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 統一錯誤 envelope */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 統一錯誤 envelope */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    sync_site_map_v1_admin_site_map_sync_post: {
        parameters: {
            query?: never;
            header?: {
                "X-Admin-Key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SiteMapSyncResponse"];
                };
            };
            /** @description 統一錯誤 envelope */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 統一錯誤 envelope */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description 統一錯誤 envelope */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 統一錯誤 envelope */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 統一錯誤 envelope */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    crawl_status_v1_admin_crawl_status_get: {
        parameters: {
            query?: never;
            header?: {
                "X-Admin-Key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CrawlStatusResponse"];
                };
            };
            /** @description 統一錯誤 envelope */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 統一錯誤 envelope */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description 統一錯誤 envelope */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 統一錯誤 envelope */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 統一錯誤 envelope */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    crawl_status_v1_admin_site_map_crawl_status_get: {
        parameters: {
            query?: never;
            header?: {
                "X-Admin-Key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CrawlStatusResponse"];
                };
            };
            /** @description 統一錯誤 envelope */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 統一錯誤 envelope */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description 統一錯誤 envelope */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 統一錯誤 envelope */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 統一錯誤 envelope */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    schedule_crawl_v1_admin_crawl_schedule_post: {
        parameters: {
            query?: never;
            header?: {
                "X-Admin-Key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["CrawlScheduleRequest"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CrawlScheduleResponse"];
                };
            };
            /** @description 統一錯誤 envelope */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 統一錯誤 envelope */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 統一錯誤 envelope */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 統一錯誤 envelope */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 統一錯誤 envelope */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 統一錯誤 envelope */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    schedule_crawl_v1_admin_site_map_crawl_schedule_post: {
        parameters: {
            query?: never;
            header?: {
                "X-Admin-Key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["CrawlScheduleRequest"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CrawlScheduleResponse"];
                };
            };
            /** @description 統一錯誤 envelope */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 統一錯誤 envelope */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 統一錯誤 envelope */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 統一錯誤 envelope */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 統一錯誤 envelope */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 統一錯誤 envelope */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
